# Generated by Django 5.1.5 on 2025-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(db_column='Nazwa', default='Zadanie 1', max_length=255)),
                ('Status', models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiązany', 'Rozwiązany')], db_column='Status', default='Nowy', max_length=50)),
                ('Przypisany_uzytkownik', models.CharField(blank=True, choices=[('Adam', 'Adam'), ('Daniel', 'Daniel'), ('Michał', 'Michał'), ('Paweł', 'Paweł'), ('Angelika', 'Angelika')], db_column='Przypisany_uzytkownik', max_length=50, null=True)),
                ('Opis', models.TextField(blank=True, db_column='Opis', null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
