# Generated by Django 5.1.5 on 2025-01-29 20:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('ID', models.IntegerField(blank=True, db_column='ID', db_index=True)),
                ('Nazwa', models.CharField(db_column='Nazwa', default='Zadanie 1', max_length=255)),
                ('Status', models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiązany', 'Rozwiązany')], db_column='Status', default='Nowy', max_length=50)),
                ('Przypisany_uzytkownik', models.CharField(blank=True, choices=[('Adam', 'Adam'), ('Daniel', 'Daniel'), ('Michał', 'Michał'), ('Paweł', 'Paweł'), ('Angelika', 'Angelika')], db_column='Przypisany_uzytkownik', max_length=50, null=True)),
                ('Opis', models.TextField(blank=True, db_column='Opis', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
