# Generated by Django 5.1.6 on 2025-02-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_historicaltask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='Nazwa',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='Opis',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='Przypisany_uzytkownik',
            new_name='przypisany_uzytkownik',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Nazwa',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Opis',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Przypisany_uzytkownik',
            new_name='przypisany_uzytkownik',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
    ]
